### ISSUE TITLE
Add in Flash Attention?

### ISSUE THREAD

**Issue by shaltielshmid** [biegehydra/NanoGptDotnet#2]
Looks like a great project! I'm a big fan of language models being written in TorchSharp. 
I just released an extension library wrapping Flash Attention (see [here](https://github.com/dotnet/TorchSharp/discussions/1231)), which perhaps can be a good addition to the project, when running on cuda?

See the original flash attention repository here: https://github.com/Dao-AILab/flash-attention

**Comment by biegehydra** [comment]
The purpose of this project was to provide a follow along project in C# for a demo that Andrej Karpathy wrote in python. That demo didn't use flash attention so I will have so say no to adding it to the main branch but I have no problem with you creating a separate branch that uses it.
